### ISSUE TITLE
PYTORCH_CUDA_ALLOC_CONF

### ISSUE THREAD

**Issue by seren4de** [seren4de/overflow_ft#1]
--> STEP: 67/193 -- GLOBAL_STEP: 20568
     | > loss: -1.33894  (-1.13225)
     | > avg_text_length: 62.66667  (37.15324)
     | > avg_spec_length: 310.13336  (195.67911)
     | > avg_text_batch_occupancy: 0.77366  (0.63137)
     | > avg_spec_batch_occupancy: 0.97526  (0.96466)
     | > amp_scaler: 8192.00000  (8314.26866)
     | > grad_norm: 1.21715  (3.87559)
     | > current_lr: 0.00100 
     | > step_time: 3.12180  (1.70437)
     | > loader_time: 0.00560  (0.00338)

 ! Run is removed from /home/hannibal/overflow_ft/overflow_ljspeech-July-09-2023_02+17PM-735f4f8
Traceback (most recent call last):
  File "/home/hannibal/anaconda3/envs/tts/lib/python3.7/site-packages/trainer/trainer.py", line 1591, in fit
    self._fit()
  File "/home/hannibal/anaconda3/envs/tts/lib/python3.7/site-packages/trainer/trainer.py", line 1544, in _fit
    self.train_epoch()
  File "/home/hannibal/anaconda3/envs/tts/lib/python3.7/site-packages/trainer/trainer.py", line 1309, in train_epoch
    _, _ = self.train_step(batch, batch_num_steps, cur_step, loader_start_time)
  File "/home/hannibal/anaconda3/envs/tts/lib/python3.7/site-packages/trainer/trainer.py", line 1150, in train_step
    num_optimizers=1,
  File "/home/hannibal/anaconda3/envs/tts/lib/python3.7/site-packages/trainer/trainer.py", line 1025, in _optimize
    outputs, loss_dict = self._model_train_step(batch, model, criterion)
  File "/home/hannibal/anaconda3/envs/tts/lib/python3.7/site-packages/trainer/trainer.py", line 970, in _model_train_step
    return model.train_step(*input_args)
  File "/home/hannibal/TTS/TTS/tts/models/overflow.py", line 178, in train_step
    mel_len=mel_lengths,
  File "/home/hannibal/TTS/TTS/tts/models/overflow.py", line 147, in forward
    encoder_outputs, encoder_output_len, z, z_lengths
  File "/home/hannibal/anaconda3/envs/tts/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hannibal/TTS/TTS/tts/layers/overflow/neural_hmm.py", line 131, in forward
    mean, std, transition_vector = checkpoint(self.output_net, h_memory, inputs)
  File "/home/hannibal/anaconda3/envs/tts/lib/python3.7/site-packages/torch/utils/checkpoint.py", line 249, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/home/hannibal/anaconda3/envs/tts/lib/python3.7/site-packages/torch/utils/checkpoint.py", line 107, in forward
    outputs = run_function(*args)
  File "/home/hannibal/anaconda3/envs/tts/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hannibal/TTS/TTS/tts/layers/overflow/common_layers.py", line 193, in forward
    ar_mels = self.parametermodel(ar_mels)
  File "/home/hannibal/anaconda3/envs/tts/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hannibal/TTS/TTS/tts/layers/overflow/common_layers.py", line 135, in forward
    x = F.relu(layer(x))
  File "/home/hannibal/anaconda3/envs/tts/lib/python3.7/site-packages/torch/nn/functional.py", line 1457, in relu
    result = torch.relu(input)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 12.00 MiB (GPU 0; 5.79 GiB total capacity; 4.28 GiB already allocated; 3.19 MiB free; 4.52 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by seren4de** [comment]
fixed in `eb61a8e1c815b304549d72c463b2e53fc4f9a04c`
